name: bookbox
description: "Bookbox"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-42.2.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.3
  flutter_riverpod: ^2.3.6
  dio: ^5.3.2
  pretty_dio_logger:
  flutter_dotenv:
  connectivity_plus: ^5.0.1
  flutter_secure_storage:
  intl: ^0.18.1
  cached_network_image:
  smooth_star_rating_null_safety:
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.0.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  calendar_date_picker2: ^0.5.3
  geolocator: ^9.0.2

  flutter_pdfview: ^1.3.2

  fluttertoast:
  flutter_screenutil:
  auto_route_generator:
  json_annotation:
  freezed_annotation:
  riverpod_annotation:
  logging:
  sendbird_chat_sdk: ^4.1.1
  scrollable_positioned_list: ^0.2.3
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed:
  build_runner:
  json_serializable:
  riverpod_generator:
  flutter_gen_runner:
  import_sorter:
  dart_code_metrics:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/books/
